### ISSUE TITLE
Include Show-TaskHelp into the Invoke-Build script

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#170] opened 2020-09-01 16:21 UTC
I use Invoke-Build version embedded into repository. In that case Show-TaskHelp and -WhatIf do not work which is kinda annoying and above all not correct behavior.

**Comment by nightroman** [comment] 2020-09-01 18:07
Do you use just the main script `Invoke-Build.ps1` in your repository, i.e. without other package files?

**Comment by majkinetor** [comment] 2020-09-01 18:16
Yah, I just copy the latest version when I start the new project to the root of the monorepo, then each subproject relies on it for local and CI runs.

I don't believe common parameter such as `WhatIf` should rely on 'external' scripts. As far as I remember you wanted it that way until it is shown to have merit.

**Comment by nightroman** [comment] 2020-09-01 18:49
I understand the inconveniences in your scenario. You miss many other features, too. The whole help, `Resolve-MSBuild`, persistent and parallel builds. If you use just the main script instead of the package then you kind of accept this.

> I don't believe common parameter such as WhatIf should rely on 'external' scripts.

I understand again. But if you use the official package then it does not rely on 'external' scripts.

> As far as I remember you wanted it that way until it is shown to have merit.

It was designed this way when `WhatIf` was doing something completely different, very lightweight, just a few extra tweaks in the main script. Then `WhatIf` became quite evolved and was deliberately moved out of the main script. I still think this is the right design decision for normal scenarios, i.e. when IB is used as one of the official packages.

If you need extras, can you add the copies of them in addition to `Invoke-Build.ps1`? `Show-TaskHelp.ps1` specifically.

**Comment by majkinetor** [comment] 2020-09-01 19:30
> You miss many other features, too. The whole help, Resolve-MSBuild, persistent and parallel builds. If you use just the main script instead of the package then you kind of accept this.

Resolve-MSBuild is IMO artifact of historic times. With core you don't really need it. Persistent and parallel builds and other stuff are not really that important for every day life. I rarely use them, they may be tricky and hard to get right, and didn't notice many in the wild either. Documentation is every day thing, however. I also think task name auto completion should be first class citizen - exactly 0  teammates had it except me and it is something even more important then docs - i use it each time I use ib, and also design task names in order to be easy to run anything with 1 or 2 letters.

> If you need extras, can you add the copies of them in addition to Invoke-Build.ps1? Show-TaskHelp.ps1 specifically

Kinda noisy. I guess I would have to explain to bunch of people to ignore it in the root of the repo.

Anyway, I am not so sure about your motivation to keep them separate. At this point of maturity you should IMO reconsider - for end user perspective there is nothing comparable to single portable file.

**Comment by nightroman** [comment] 2020-09-01 20:06
> Kinda noisy. I guess I would have to explain to bunch of people to ignore it in the root of the repo.

You may keep them in a directory, say, `scripts`.

> Anyway, I am not so sure about your motivation to keep them separate. At this point of maturity you should IMO reconsider - for end user perspective there is nothing comparable to single portable file.

I am not sure that the scenario you use is common and many other users are interested.

IB is mature but not done, as far as I use it, at least. It will change and evolve. It will probably have more satellite tools like `Show-TaskHelp.ps1`. If we embed one then all should be embedded. I am not sure this is (a) effective, (b) easily maintainable. Even for one `Show-TaskHelp.ps1`. That is why it is 'external'.

You are probably disappointed. I am sorry for this. I have not done thinking about your suggestion. But something tells it is not quite right in the current IB design.

**Comment by majkinetor** [comment] 2020-09-01 21:24
> If we embed one then all should be embedded

One solution would be to do it is to merge scripts at the build time and produce alternative portable version in single file. That would solve both a) and b).

**Comment by nightroman** [comment] 2020-09-02 05:31
This would solve (b), partially, because complexity still increases. But (a) is not solved. In the current design satellite scripts are not loaded/parsed if they are not used. For example, `Show-TaskHelp.ps1` is not loaded/parsed when you invoke build scripts. This is effective. You are suggesting making it parsed always, even not used. This is ineffective. I think many users do not use `WhatIf` often or at all.

**Comment by nightroman** [comment] 2020-09-02 06:03
Let me discuss the other points you mentioned.

> Resolve-MSBuild is IMO artifact of historic times. With core you don't really need it.

True but not everything is core yet. I am sure MSBuild is still used directly by many and `Resolve-MSBuild.ps1` is needed.

> Persistent and parallel builds and other stuff are not really that important for every day life.

Agree with parallel builds (?), disagree with persistent. I know that people use it in expensive complex scenarios. I use it in one scenario. It is not everyday but I need it. Some people need it, too, #150, #140. Thus, `Build-Checkpoint.ps1` is needed.

> Regarding whole help, I yet have to see somebody reading it in posh directly instead using Internet. The convenience is not comparable.

I constantly use console help and rarely internet. And I think many people do the same. Thus, help in the package is needed.

> I also think task name auto completion should be first class citizen

I agree. Let's think how to make it better. My current approach has its pros and cons. What would you suggest instead?

**Comment by majkinetor** [comment] 2020-09-02 06:36
> This would solve (b), partially, because complexity still increases.

That would be standalone solution so it shouldn't influence other parts, for which complexity stays the same. Complexity of the build increases.

>  You are suggesting making it parsed always, even not used. This is ineffective.

It doesn't matter if we have bundled and original version so anybody can choose what to use to be most effective. The size of the ib script is IMO not important for effectiveness - its theoretically less effective but in execution practice it wont matter 1 bit. 

>> I also think task name auto completion should be first class citizen

> I agree. Let's think how to make it better

The only thing that comes to my mind besides creating some switch to add it to user profile quickly is to assure its on on any run - so as soon as I call it once (for example ib ?) it checks and if needed sources the auto complete script for itself. That way you maybe wont have it on the first run but it will still work most of the time automatically and you will be able to enable it quickly.  This would work for 'standalone' scripts too. 

Maybe posh DynamicParams could be used as well - you create dynamic Tasks param with dynamic ValidateSet attribute that will allow for completion.  That should always work.


Regarding other things, I believe the best option that will satisfy both you as developer and me/us as end users is to dynamically create standalone script and offer it on GH releases or  include it in the module (`standalone\Invoke-Build.ps1`). I sure wont mind added inefficiency :)

Thanks for discussion @nightroman.

**Comment by nightroman** [comment] 2020-09-03 04:52
For the movement I am not going to make any official changes.
I am not sure that the scenario is common enough.
We will see if more users need this.

But I listen and want to help. Use the below script for building your own portable IB.

*Build-IBPortable.ps1*

```powershell
<#
.Synopsis
    Builds portable Invoke-Build.ps1.

.Parameter IBRoot
        Invoke-Build source directory, package or repository.

.Parameter Output
        Output file path. The file must not exist.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=1)]
    $IBRoot,
    $Output = 'Invoke-Build.ps1'
)

$ErrorActionPreference = 1
if (Test-Path -LiteralPath $Output) {throw "Output file '$Output' must not exist."}

$IBLines = Get-Content -LiteralPath (Join-Path $IBRoot Invoke-Build.ps1)
$ShowTaskHelpLines = Get-Content -LiteralPath (Join-Path $IBRoot Show-TaskHelp.ps1)

$(
    foreach($_ in $IBLines) {
        if ($_ -ceq 'Set-Alias Show-TaskHelp (Join-Path $_ Show-TaskHelp.ps1)') {
            'function Show-TaskHelp {'
            $ShowTaskHelpLines
            '}'
        }
        else {
            $_
        }
    }
) | Set-Content -LiteralPath $Output
```

**Comment by nightroman** [comment] 2020-09-08 17:59
@majkinetor 
I am closing this issue. The solution is not what you asked for, I understand this and apologize if you are disappointed. But it is the solution for your use case using some not standard packaging. The mainstream Invoke-Build is designed as a package with several pieces, for various reasons.

**Closed by nightroman** 2020-09-08 17:59 UTC

**Comment by majkinetor** [comment] 2020-09-08 18:58
OK, not sure why you don't include `Build-IBPortable.ps1` among other scripts tho (once it is complete).
