### ISSUE TITLE
v3.3.9 does not export any commands on PS Core

### ISSUE THREAD

**Issue by PowerSchill** [nightroman/Invoke-Build#71] opened 2017-05-23 13:01 UTC
Tested on OS10.12 and Ubuntu 16.04.1

**Comment by nightroman** [comment] 2017-05-23 13:05
Did you import the module?

**Comment by PowerSchill** [comment] 2017-05-23 13:13
I see the issue now. PS Core apparently has an issue with aliases not being exported.

**Comment by nightroman** [comment] 2017-05-23 13:30
I have just tried with PS Core 6.0.0-beta.1-win81-win2012r2-x64

    PS> ipmo 'C:\Program Files\WindowsPowerShell\Modules\InvokeBuild'
    PS> gal *build*

    CommandType     Name                                               Version    Source
    -----------     ----                                               -------    ------
    Alias           Invoke-Build                                       3.3.9      InvokeBuild
    Alias           Invoke-Builds                                      3.3.9      InvokeBuild

Also, according to https://github.com/nightroman/Invoke-Build/issues/69, InvokeBuild (the module, see paths) works on PowerShell core on MacOSX: v6.0.0-alpha.18 or v6.0.0-beta.1

So not every PS Core has this problem.

**Comment by PowerSchill** [comment] 2017-05-23 13:49
Yeah, once I import the module it is available but it is not discoverable. 

```
LogPipelineExecutionDetails : False
Name                        : InvokeBuild
Path                        : /usr/local/microsoft/powershell/6.0.0-beta.1/Modules/InvokeBuild/3.3.9/InvokeBuild.psd1
ImplementingAssembly        :
Definition                  :
Description                 : Build and test automation in PowerShell
Guid                        : a0319025-5f1f-47f0-ae8d-9c7e151a5aae
HelpInfoUri                 :
ModuleBase                  : /usr/local/microsoft/powershell/6.0.0-beta.1/Modules/InvokeBuild/3.3.9
PrivateData                 : {PSData}
Tags                        : {Build, Test, Automation, Build...}
ProjectUri                  : https://github.com/nightroman/Invoke-Build
IconUri                     : https://raw.githubusercontent.com/nightroman/Invoke-Build/master/ib.png
LicenseUri                  : http://www.apache.org/licenses/LICENSE-2.0
ReleaseNotes                : https://github.com/nightroman/Invoke-Build/blob/master/Release-Notes.md
RepositorySourceLocation    : https://www.powershellgallery.com/api/v2/
Version                     : 3.3.9
ModuleType                  : Script
Author                      : Roman Kuzmin
AccessMode                  : ReadWrite
ClrVersion                  :
CompanyName                 : Roman Kuzmin
Copyright                   : (c) 2011-2017 Roman Kuzmin
DotNetFrameworkVersion      :
ExportedFunctions           : {}
Prefix                      :
ExportedCmdlets             : {}
ExportedCommands            : {}
FileList                    : {}
CompatiblePSEditions        : {}
ModuleList                  : {}
NestedModules               : {}
PowerShellHostName          :
PowerShellHostVersion       :
PowerShellVersion           : 2.0
ProcessorArchitecture       : None
Scripts                     : {}
RequiredAssemblies          : {}
RequiredModules             : {}
RootModule                  : InvokeBuild.psm1
ExportedVariables           : {}
ExportedAliases             : {}
ExportedWorkflows           : {}
ExportedDscResources        : {}
SessionState                :
OnRemove                    :
ExportedFormatFiles         : {}
ExportedTypeFiles           : {}
```

**Comment by nightroman** [comment] 2017-05-23 15:26
So it looks like the empty

    ExportedAliases             : {}

is the only defect (of PS Core). But Invoke-Build works. If this is correct we may close the issue.

**Comment by nightroman** [comment] 2017-05-24 01:57
I am closing this. Presumably, there is nothing wrong with Invoke-Build. Are you going to open an issue about empty `ExportedAliases` at https://github.com/PowerShell/PowerShell ? I would open it myself but I have no chance to reproduce in order to describe and follow.

**Comment by dbroeglin** [comment] 2017-05-24 17:56
I agree the issue is most probably not related to Invoke-Build but because I just had to upgrade to 3.3.9 anyway due to #69 I ran the following test on **PS Core 6 beta 1 Windows**:

With only 3.3.9 installed, I see the aliases:

```
PS C:\Windows\system32> get-module -l invokebuild


    Directory: C:\program files\powershell\6.0.0-beta.1\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.3.9      InvokeBuild                         {Invoke-Builds, Invoke-Build}

```

If I reinstall 3.3.8, I see the aliases for 3.3.9 and not for 3.3.8 :

```
PS C:\Windows\system32> install-module invokebuild -requiredversion 3.3.8
PS C:\Windows\system32> get-module -l invokebuild


    Directory: C:\program files\powershell\6.0.0-beta.1\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.3.9      InvokeBuild                         {Invoke-Builds, Invoke-Build}
Script     3.3.8      InvokeBuild
```

The behaviour was reversed just after an `Update-Module` from 3.3.8 to 3.3.9. So I guess the order in which the modules are inspected (which seems to be dependent on the filesystem or last created directory) causes those symptoms. The first module to be inspected will have the aliases exported but not the second (maybe because the second did already export them ?)

I also get an interesting behaviour with exportedAliases:

```
PS C:\Windows\system32> (get-module -l invokebuild)  | Select-Object name,version,@{n='a'; e={$_.exportedaliases }}

Name        Version a
----        ------- -
InvokeBuild 3.3.9   {[Invoke-Builds, Invoke-Builds], [Invoke-Build, Invoke-Build]}
InvokeBuild 3.3.8   {}
```


On "PS Core 6 beta 1 Mac OS X" however I do not see the aliases at all:

```
PS /Users/dom/Tmp/ps-csv> get-module invokebuild -l

    Directory: /Users/dom/.local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.3.9      InvokeBuild
Script     3.3.8      InvokeBuild
```

Same for exported aliases:

```
PS /Users/dom/Tmp/ps-csv>  (get-module -l invokebuild)  | Select-Object name,version,@{n='a'; e={$_.exportedaliases }}

Name        Version a
----        ------- -
InvokeBuild 3.3.9   {}
InvokeBuild 3.3.8   {}
```

So there is at least an inconsistency between the platforms for a same version of PS Core.

**Comment by dbroeglin** [comment] 2017-05-24 19:17
Adding : 
```
	AliasesToExport = @('Invoke-Build', 'Invoke-Builds')
```
to both PSD1 files ensures that the aliases are always exported.

**Comment by nightroman** [comment] 2017-05-24 19:23
@dbroeglin , do you mean adding to psd1 in addition to 

    Export-ModuleMember -Alias Invoke-Build, Invoke-Builds

in psm1? I am reopening then. Good catch, thank you!

**Comment by dbroeglin** [comment] 2017-05-24 19:52
Yes, this is a purely experimental result as the documentation does not say that. From: https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/new-modulemanifest  :

> -AliasesToExport
> 
> Specifies the aliases that the module exports. Wildcard characters are permitted.
> 
> You can use this parameter to restrict the aliases that are exported by the module. It can remove aliases from the list of exported aliases, but it cannot add aliases to the list.
> 
> If you omit this parameter, New-ModuleManifest creates an AliasesToExport key with a value of * (all), meaning that all aliases that are exported by the module are exported by the manifest.

At some point I thought it was because you did not leave 

```
	AliasesToExport = '*'
```

which is the default value set by `New-ModuleManifest` and should tell the PS to export all aliases defined in   `Export-ModuleMember`. But adding only '*' does not work either on MacOSX. Only adding the list explicitly.

**Comment by nightroman** [comment] 2017-05-24 20:52
Thank you. It will be added in the next version.

**Closed** 2017-05-25 18:04 UTC

**Comment by nightroman** [comment] 2017-05-25 18:09
v3.3.10 addresses this defect. Hopefully, because I cannot test on my own. Please let me know how it goes.

**Comment by PowerSchill** [comment] 2017-05-26 12:45
Just pulled the latest from the Gallery on OSX and the commands are exported. Thanks very much.

**Comment by dbroeglin** [comment] 2017-05-26 13:03
Same here on MacOSX and Windows 10. After a module upgrade the aliases are found for v3.3.10.
Nice work!

Side note (nothing to do with InvokeBuild): now I have a weird behaviour with completion. "Invoke-G" would complete as Invoke-Gherkin or Invoke-Git but "Invoke-B" will not complete (both Invoke-Build and Invoke-Builds appear in the completion list but the completion does not occur)

I think there are some weird bugs in Alias support from within modules. Do you plan on reporting the issues we face to the PS team ? If not I will make a note to do it latter with a simple reproducer that does not involve Invoke-Build but I'm not sure when I will have time to do it.

**Comment by nightroman** [comment] 2017-05-26 13:23
@PowerSchill and @dbroeglin 
Thank you for the report and the suggested fix.

> Do you plan on reporting the issues we face to the PS team ?

No, I do not. Windows is my only OS. I would not like to report anything that I cannot repro and follow myself.
