### ISSUE TITLE
The `Task` line doesn't include the `Synopsis`

### ISSUE THREAD

**Issue by DavidSimner** [nightroman/Invoke-Build#98] opened 2017-11-03 13:50 UTC
Given this input:
```
Invoke-Build -File {
  # Synopsis: Hello...
  task . {
    Write-Output '... World!'
  }
}
```

Version `3.7.1` of `InvokeBuild` outputs:
```
Build . C:\git\project\run-build.ps1
Task /.
... World!
Done /. 00:00:00.0054870
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.1285303
```

Whereas, it would be nice if the `Synopsis` was shown too, e.g. the output would be nicer as:
```
Build . C:\git\project\run-build.ps1
Task /.  Hello...
... World!
Done /. 00:00:00.0054870
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.1285303
```

**Comment by nightroman** [comment] 2017-11-03 14:21
Well... compare: you have a PowerShell script with help comments with a synopsis. It would not be nicer if this synopsis is printed when we run the script.

**Comment by nightroman** [comment] 2017-11-03 14:37
I think it is not a good idea to mix help info and runtime work. At least not by default.
If you want to decorate your tasks with their synopsizes, see this sample:
https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Header

**Comment by nightroman** [comment] 2017-11-03 14:50
Out of curiosity, do you know other build tools which show tasks/targets synopsizes?

**Comment by DavidSimner** [comment] 2017-11-03 15:21
I was trying to make it easy for other devs, who hadn't seen the build script before, to read the build log and understand what was happening from that alone.  The `task` structure of `Invoke-Build` encourages tasks with short names, but sometimes in a short name it is difficult to convey all the information that people need.  I pondered adding `Write-Build` or `Write-Output` lines but felt that they would often duplicate the `Synopsis`, so I wondered if the `Synopsis` could just be printed instead.

I feel that `Invoke-Build` encourages short task names (because space isn't allowed in them), whereas say TeamCity encourages longer and more descriptive names (because spaces are allowed):
![image](https://user-images.githubusercontent.com/2973219/32381095-c6463f4c-c0a9-11e7-87ce-a859c577559d.png)
By encouraging longer and more descriptive names, other build tools don't need the 'feature' of showing the `Synopsis` because there's enough information shown already.

Also, a build tool that shows synopsizes is for example `csc`.
By default, when you run `csc` with no arguments it shows:
```
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified
```

Those first 2 lines are basically a synopsis that this is the `Microsoft Visual C# Compiler blah blah`.  You can turn the summary off with `/nologo` if you don't want it.

**Comment by DavidSimner** [comment] 2017-11-03 15:23
Thanks for the pointer to https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Header :)

**Comment by nightroman** [comment] 2017-11-03 15:46
> Invoke-Build encourages short task names (because space isn't allowed in them)

Not true. You can use any name you like, e.g.

```
task 'Step 1/3: foo bar' {...}
```

It's up to you. If you do not mind to type these names on invocations then why not? Especially if such task names are not often called explicitly from a command line.

> Also, a build tool that shows synopsizes is for example csc. By default, when you run csc with no arguments it shows:

I am sorry, but you talking about something else. `csc` is not a build tool. A build tool is MSBuild. It shows task (target) names and nothing else. And other popular build tools show task names.

----

All in all, this is not a bug and I do not want to add this as a feature for several reasons:

- in many cases such info is noise
- other build tools do not do this
- if you want this you can do this (see the provided sample)

If you agree let's close this issue.

**Closed** 2017-11-03 16:17 UTC
