### ISSUE TITLE
Job/Task execution order issue when combined with -Before

### ISSUE THREAD

**Issue by icraftsoftware** [nightroman/Invoke-Build#96] opened 2017-11-01 18:45 UTC
Hello,

I am troubled with the task/job execution order of Invoke-Build v 3.7.1. Given this very simple script, named `deploy.build.ps1`:

```PowerShell
task Deploy Deploy-Assemblies
task Undeploy Undeploy-Assemblies
task Deploy-Assemblies Undeploy-Assemblies, { }
task Undeploy-Assemblies { }
task -Name Load-Assemblies -Before Deploy, Undeploy -Jobs { }
```

It outputs the following, when invoked via `Invoke-Build -Task Deploy`:

```
Build Deploy C:\Files\...\deploy.build.ps1
Task /Deploy/Deploy-Assemblies/Undeploy-Assemblies
Done /Deploy/Deploy-Assemblies/Undeploy-Assemblies 00:00:00.0030017
Task /Deploy/Deploy-Assemblies
Done /Deploy/Deploy-Assemblies 00:00:00.0060039
Task /Deploy/Load-Assemblies
Done /Deploy/Load-Assemblies 00:00:00.0030014
Done /Deploy 00:00:00.0100067
```

I do not understand why `Load-Assemblies` is executed last and not as the very first job/task. If I changed the -Before clause as follows `-Before Deploy-Assemblies, Undeploy-Assemblies` then it works as expected. What is the nuance? I would consider this as a bug! But if not could you shed some light on the why and provide some guidance?

Note that the output is similar and this issue still exists when invoked via `Invoke-Build -Task Undeploy`.

(As a side note. Changing the `-Before` clause is not what I want to do, I need `Load-Assemblies` to be executed before any subtask of `Deploy`, which are many in a real-life script. That is to say I don't want to repeat the `Deploy`'s whole list of dependencies in the `-Before` clause of `Load-Assemblies`.

But then maybe you have a better suggestion to achieve what I try to do: I want to dot source a bunch of .tasks.ps1 files in a deploy.build.ps1. This deploy.build.ps1 provision a series of script variables that are used by the dot sourced tasks. Hence the need to perform the provisioning before any dot sourced task is ever executed. I am sure there is a simpler way, like regular powershell statements... but what I like very much about `Invoke-Build` is that it ensures a.o. that each task has an expected current-location and does a great job to prevent you from messing around with it. The files I am dot sourcing are really coming from a bunch of folders, which should be left open to preferences/customization and not be fixed.)

Thank you very much.

François

**Comment by nightroman** [comment] 2017-11-01 19:39
One question at a time :) The first:

> I do not understand why Load-Assemblies is executed last and not as the very first job/task.

Because you do not ask (program) it to be the very first task. You ask it to be
invoked `-Before Deploy, Undeploy`. `Undeploy` is not involved in the build.
`Deploy` is involved and `Load-Assemblies` is invoked "before it" (in a way!).

To make this clear, let's add some output to your tasks:

```powershell
task Deploy Deploy-Assemblies, {$Task.Name}
task Undeploy Undeploy-Assemblies, {$Task.Name}
task Deploy-Assemblies Undeploy-Assemblies, {$Task.Name}
task Undeploy-Assemblies {$Task.Name}
task -Name Load-Assemblies -Before Deploy, Undeploy -Jobs {$Task.Name}
```

Output:

```
Build Deploy C:\ROM\z\_171101_184915_ib_96\.build.ps1
Task /Deploy/Deploy-Assemblies/Undeploy-Assemblies
Undeploy-Assemblies
Done /Deploy/Deploy-Assemblies/Undeploy-Assemblies 00:00:00
Task /Deploy/Deploy-Assemblies
Deploy-Assemblies
Done /Deploy/Deploy-Assemblies 00:00:00
Task /Deploy/Load-Assemblies
Load-Assemblies
Done /Deploy/Load-Assemblies 00:00:00.0156058
Task /Deploy
Deploy
Done /Deploy 00:00:00.0156058
Build succeeded. 4 tasks, 0 errors, 0 warnings 00:00:00.0781464
```

You see, "Deploy" is printed after "Load-Assemblies".

Your example has the different log and makes you confused. Do not be confused,
understand the log and the flow of actions. Here is the last piece of your log:

```
...
Done /Deploy/Load-Assemblies 00:00:00.0030014
Done /Deploy 00:00:00.0100067
```

It says: Finished Load-Assemblies which is called by Deploy, "Done /Deploy/Load-Assemblies".
Then: Deploy is resumed and it has nothing to do itself, so there is nothing to log but "Done /Deploy".

In my extended example, Deploy has own action, so that we can see this fact reflected in my log.

***

Now, let's understand what `task Load-Assemblies -Before Deploy { }` really means.
It means, "When Deploy is invoked, do Load-Assemblies before own actions of Deploy".
You see, the task Deploy, as a whole, is actually invoked first. But it calls
Load-Assemblies first and then runs its own action, if any. Your example does
not have any, so it does not matter. My example does, and this action is
invoked after Load-Assemblies, as required.

Phew... Does this make sense?

**Comment by nightroman** [comment] 2017-11-01 20:01
> I want to dot source a bunch of .tasks.ps1 files in a deploy.build.ps1. This
deploy.build.ps1 provision a series of script variables that are used by the
dot sourced tasks. Hence the need to perform the provisioning before any dot
sourced task is ever executed.

I normally recommend to avoid using `-Before` and `-After` instead of
specifying task dependencies in a normal way. See [Build-Scripts-Guidelines](https://github.com/nightroman/Invoke-Build/wiki/Build-Scripts-Guidelines#do-not-overuse--before-and--after).

But your scenario with imported tasks may be a legit use case. If you want to
alter some tasks jobs without modifying those tasks code then `-Before` and
`-After` is the right way to go.

**Comment by nightroman** [comment] 2017-11-01 20:37
BTW, if you really want `Load-Assemblies` to be the very first then you have to
specify all possible related tasks in its `-Before`. This may be not the best
thing to do.

I do not know your exact scenario. Perhaps you want something like this:

```powershell
    ... # dot-source external tasks
    
    Enter-Build {
        # load assemblies here, always and before tasks
    }
    
    task ... # define own tasks
```

**Comment by nightroman** [comment] 2017-11-02 04:56
> If I changed the -Before clause as follows -Before Deploy-Assemblies,
Undeploy-Assemblies then it works as expected. What is the nuance? I would
consider this as a bug! But if not could you shed some light on the why and
provide some guidance?

Not a bug, this is by design. `-Before` inserts a reference before the first
action job, not before all jobs. See help:

```powershell
    . Invoke-Build
    help task -Parameter Before
```

Why? Because if you need it (`task X`) to be inserted even "before tasks in the
job list" (`task Y Z, {}`), i.e before Z, then Z per your design depends on X.
So instead of `task X -Before Y` you should do `task X -Before Z`.

All in all, I do not think there is something wrong with Invoke-Build in here.
Task relations (explicit or defined by `-Before` and `-After`) work very well.
Just think what is before what and program this accordingly.

**Comment by icraftsoftware** [comment] 2017-11-02 09:15
Hello Roman,

Thank you so much for your very fast answerS. :) You are absolutely right about the execution order! I did not thoroughly thought about it and, as you pointed out, my example was too simple to reflect the execution order with enough details. My bad! :)

The `-Before` clause's semantics is very subtle though. According to your explanation (i.e. "before its own action"), if I change the one line `Deploy` task in the sample by putting its own action before its dependencies, it works as I was expecting...
````PowerShell
task Deploy {$Task.Name}, Deploy-Assemblies
````
`Invoke-Build` is very feature rich. By just adding an action block of its own to a task, right before its dependencies, it changes the execution order of all the other tasks that have a `-Before` clause referencing this very task. I now understand why you do not recommend using `-Before` and `-After`. And I am not saying you should do anything about it: I like having a lot options... but not when it comes as a surprise.

The operational semantics of `Invoke-Build` is very rich and subtle and I think your wiki page 'How Build Works', though very comprehensive and accurate, does not do justice to it. Everything is written down, but a few words and samples about the `Invoke-Build` idioms would help... Or maybe it's because I just got bitten.

To conclude, I totally overlooked the `Enter-Build { }` function block. This is exactly what I need.

Thanks again

François

**Comment by nightroman** [comment] 2017-11-02 11:57
I am glad that it works for you now. I am closing the issue.

As for task dependencies and job order, well, this should be designed carefully and can be tricky, too. [Show-BuildGraph.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Show-BuildGraph.ps1) may help to visualize and understand things before invoking. For example, for your original sample the command `Show-BuildGraph -Number` produces:

![image](https://user-images.githubusercontent.com/927533/32324583-d3311038-bfc3-11e7-819b-9471f966caa7.png)

And for my extended sample:

![image](https://user-images.githubusercontent.com/927533/32324861-a84f2dfe-bfc4-11e7-8b0e-60ebaf6b2e9a.png)

Numbers show the order of jobs.

**Closed by nightroman** 2017-11-02 11:57 UTC
